#!/bin/bash
# deploy-vars.sh - Script para configurar variáveis de ambiente no Vercel

echo "================================"
echo "CONFIGURAÇÃO DE VARIÁVEIS - VERCEL"
echo "================================"
echo ""
echo "Execute os comandos abaixo no terminal:"
echo ""
echo "1. NEXTAUTH_SECRET (obrigatório para NextAuth funcionar):"
echo "   vercel env add NEXTAUTH_SECRET production"
echo "   Valor: FTbJBhfMXsAiuYBRIYrYFzgq3o9bnqUvZPI7qnfaiHk="
echo ""
echo "2. NEXTAUTH_URL (URL base da aplicação):"
echo "   vercel env add NEXTAUTH_URL production"
echo "   Valor: https://varejofflex-git-main-hariel-soares-marans-projects.vercel.app"
echo ""
echo "3. Para verificar variáveis existentes:"
echo "   vercel env ls"
echo ""
echo "4. Após adicionar as variáveis, fazer redeploy:"
echo "   vercel --prod"
echo ""
echo "================================"
echo "VARIÁVEIS ATUAIS NECESSÁRIAS:"
echo "================================"
echo "✅ MONGODB_URI - Configurado"
echo "❓ NEXTAUTH_SECRET - Verificar"
echo "❓ NEXTAUTH_URL - Verificar"
echo "✅ OWNER_SECRET_KEY - Configurado"
echo ""